namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- presync.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: patches/job-generate-name.yaml
  target:
    version: v1
    kind: Pod
    name: presync-pod-
