namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- presync.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: patches/job-generate-name.yaml
  target:
    group: batch
    version: v1
    kind: Job
    name: presync-job-
- path: patches/job-generate-name.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Workflow
    name: gc-ttl-
