apiVersion: v1
kind: Pod
metadata:
  name: presync-pod-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  containers:
  - name: sleep
    image: alpine:latest
    command: ["sleep", "10"]
  restartPolicy: Never
